/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CogModUiModule extends AbstractCogModUiModule {

	public CogModUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
