/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCogModScopeProvider extends DelegatingScopeProvider {
}
