/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.parser.antlr;

import com.google.inject.Inject;
import eu.coresense.cognitivemodule.parser.antlr.internal.InternalCogModParser;
import eu.coresense.cognitivemodule.services.CogModGrammarAccess;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CogModParser extends AbstractAntlrParser {

	@Inject
	private CogModGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new CogModTokenSource(super.createLexer(stream));
	}
	
	/**
	 * Indentation aware languages do not support partial parsing since the lexer is inherently stateful.
	 * Override and return {@code true} if your terminal splitting is stateless.
	 */
	@Override
	protected boolean isReparseSupported() {
		return false;
	}

	@Override
	protected InternalCogModParser createParser(XtextTokenStream stream) {
		return new InternalCogModParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CognitiveModule";
	}

	public CogModGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CogModGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
