/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CogModAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/coresense/cognitivemodule/parser/antlr/internal/InternalCogModParser.tokens");
	}
}
