/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CogModProposalProvider extends AbstractCogModProposalProvider {
}
