/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CogModRuntimeModule extends AbstractCogModRuntimeModule {
}
