/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule;

//import org.eclipse.emf.common.util.URI;
//import org.eclipse.emf.ecore.resource.Resource;
//import org.eclipse.emf.ecore.resource.ResourceSet;
//import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
//import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CogModStandaloneSetup extends CogModStandaloneSetupGenerated {

	public static void doSetup() {
		new CogModStandaloneSetup().createInjectorAndDoEMFRegistration();
//		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("ecore", new EcoreResourceFactoryImpl());
//		URI uri = URI.createURI("platform:/resource/eu.coresense.CognitiveModule/model/CognitiveModule.ecore");
//		ResourceSet rs = new ResourceSetImpl();
//		rs.getResource(uri, true);
	}
}
