/*
 * generated by Xtext 2.38.0
 */
package eu.coresense.cognitivemodule.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.coresense.cognitivemodule.CogModRuntimeModule;
import eu.coresense.cognitivemodule.CogModStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CogModIdeSetup extends CogModStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CogModRuntimeModule(), new CogModIdeModule()));
	}
	
}
